Telefonica/mistica-android

.github/workflows/release.yml
Workflow-dispatch actions are only usable with write permissions. That should be enough for us.
=> ANDROID-9698 Removing admin check in workflow_dispatch

README.md, library-compose/README.md, library-compose/src/main/java/com/telefonica/mistica/compose/button/README.md, library-compose/src/main/java/com/telefonica/mistica/compose/feedback/README.md
Adding documentation regarding compose
[See the result here](https://github.com/Telefonica/mistica-android/tree/compose-documentation)
=> Update documentation regarding compose

catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/CatalogMainActivity.kt, library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/O2Brand.kt, library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/O2ClassicBrand.kt
Implement O2 brand in compose
* Just add new brand based on xml theme
=> ANDROID-10005 Compose brand o2

catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/CatalogMainActivity.kt, library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/BlauBrand.kt, library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/O2Brand.kt, library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/O2ClassicBrand.kt
Implement Blau brand in compose
* Just add new brand based on xml theme
=> ANDROID-10007 Compose brand blau

catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Buttons.kt, library-compose/src/main/java/com/telefonica/mistica/compose/button/Button.kt, library-compose/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt, library-compose/src/main/java/com/telefonica/mistica/compose/shape/Chevron.kt, library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/BlauBrand.kt, library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/MovistarBrand.kt, library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/O2Brand.kt, library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/O2ClassicBrand.kt, library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/TelefonicaBrand.kt, library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/VivoBrand.kt
Adding a modifier parameter in the Button composable
Adding the modifier and propagating it to the AndroidView
Also some minor fixes in the UI and some imports that were wrong
=> Modifier to buttons

.github/workflows/snapshot.yml, app/src/main/java/com/telefonica/mistica/app/CatalogApplication.kt, build.gradle
Adding support for releasing snapshots
Just adding the action and setting properly the version
=> ANDROID-10255 - Adding support for snapshots

.github/PULL_REQUEST_TEMPLATE.md
Added to PR template a checkbox to remember dowload link for Mística App or a QR
=> PR Template changes

.github/workflows/catalog.yml, .github/workflows/promote_release.yml, .github/workflows/release.yml, .github/workflows/tests.yml
Update docker image from version 1 to version 2
* Search al references to _docker://docker.tuenti.io/android/novum_android_api31:1_
* Replace with _docker://docker.tuenti.io/android/novum_android_api31:2_
=> ANDROID-10866 Update docker image to version 2

.github/workflows/link_checker.yml
You can trigger this action manually to know if there exist links broken in this repo.
At this moment there is a lot through the markdown documentation
https://github.com/Telefonica/mistica-android/actions/runs/2919732253
=> Link checker action

catalog/src/main/java/com/telefonica/mistica/catalog/ui/fragment/PopOverCatalogFragment.kt, catalog/src/main/res/layout/screen_popovers_catalog.xml, library/src/main/java/com/telefonica/mistica/feedback/popover/PopOver.kt, library/src/main/java/com/telefonica/mistica/feedback/popover/PopOverData.kt, library/src/main/java/com/telefonica/mistica/feedback/popover/PopOverView.kt, library/src/main/java/com/telefonica/mistica/feedback/popover/README.md, library/src/main/res/layout/popover_view.xml
Force Popover position. Sometime we wanted to show the Popover in a custom position.
Pass a optional attribute and check it.
https://user-images.githubusercontent.com/8106237/191231100-88be89e0-4200-4897-96eb-51518c32b019.mov
=> ANDROID 11075 Force Popover position

library/src/main/res/values/themes_movistar.xml, library/src/main/res/values/themes_o2.xml, library/src/main/res/values/themes_o2_classic.xml, library/src/main/res/values/themes_telefonica.xml, library/src/main/res/values/themes_vivo.xml
=> change color in backgroundSkeleton

library/src/main/java/com/telefonica/mistica/sheet/children/list/adapter/ActionsListAdapter.kt
Adding the ripple effect like the one we have in rows into Actions.
Reusing the same drawable as the rows, since I assume it will always be the same.
https://user-images.githubusercontent.com/4595241/197482568-0c98a292-14a5-4d5e-b90c-98d7915f6f13.mp4
=> ANDROID-11232 Adding ripple to actions

catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/CatalogMainActivity.kt, catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Callouts.kt, catalog-compose/src/main/res/drawable/ic_callout.xml, catalog/src/main/java/com/telefonica/mistica/catalog/ui/fragment/CalloutsCatalogFragment.kt, catalog/src/main/res/layout/screen_callouts_catalog.xml, library-compose/README.md, library-compose/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt, library-compose/src/main/java/com/telefonica/mistica/compose/callout/README.md, library-compose/src/main/res/layout/icn_cross.xml, library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
Compose implementation of Callout component
- Existing Callout scecs have been followed
- Added identical catalog section as non-compose one
- Appcenter Link bellow  :)
=> ANDROID-11418 Compose version of Callout

.github/workflows/catalog.yml, library/src/main/java/com/telefonica/mistica/compose/README.md, library/src/main/java/com/telefonica/mistica/title/README.md, mavencentral.gradle
=> ANDROID-11131 Change default branch to main

library/src/main/java/com/telefonica/mistica/compose/README.md
=> Fix broken link in documentation

library/src/main/java/com/telefonica/mistica/title/TitleView.kt
Add getters to Title component to be able to test it using acceptance tests
=> ANDROID-11726 Add getters to Title component

catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/CatalogMainActivity.kt, catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Tabs.kt, catalog-compose/src/main/res/drawable/ic_tab.xml, library/src/main/java/com/telefonica/mistica/compose/README.md, library/src/main/java/com/telefonica/mistica/compose/tabs/README.md, library/src/main/java/com/telefonica/mistica/compose/tabs/Tabs.kt
Implement compose tabs, following [specifications from design.](https://www.figma.com/file/tOb2OmRf6gnEK3fnSWPKOG/%F0%9F%94%B8-Tabs-Specs?node-id=309-3976&t=jTuZhrq5diuHn7sa-0)
* Implementation mostly based on material code, but changing its code to work as design specified.
* Single `Tabs` function provides tabs implementation.
https://user-images.githubusercontent.com/5360064/224015176-8cd6e671-73d6-4149-83d9-72cc608ec57a.mp4
https://appcenter-filemanagement-distrib5ede6f06e.azureedge.net/4484ec7a-d2db-4304-a306-f975463c0938/MisticaCatalog-debug-1678362841.apk?sv=2019-02-02&sr=c&sig=FlW90VdTWoDzrklfQF6j2AP0ynhhV7zNW%2BvvH0AspHw%3D&se=2023-03-10T11%3A55%3A56Z&sp=r
=> ANDROID-11510 Compose Tabs

.github/workflows/release.yml
Fix github action, Github action was wrong by removed '
* Add '
=> Fix generate release github action

catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/activity/EmptyStateScreenCatalogActivity.kt, catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/EmptyStateCardCatalogFragment.kt, catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/EmptyStateScreenCatalogFragment.kt, catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/EmptyStateCards.kt, catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/EmptyStateScreens.kt, catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Feedbacks.kt, catalog/src/main/res/layout/empty_state_card_fragment_catalog.xml, catalog/src/main/res/layout/empty_state_screen_fragment_catalog.xml, library/src/main/java/com/telefonica/mistica/compose/emptystate/card/EmptyStateCard.kt, library/src/main/java/com/telefonica/mistica/compose/emptystate/screen/EmptyStateScreen.kt, library/src/main/java/com/telefonica/mistica/compose/feedback/Feedback.kt, library/src/main/java/com/telefonica/mistica/emptystate/card/EmptyStateCardView.kt, library/src/main/java/com/telefonica/mistica/emptystate/card/README.md, library/src/main/java/com/telefonica/mistica/emptystate/screen/EmptyStateScreenView.kt, library/src/main/java/com/telefonica/mistica/emptystate/screen/README.md, library/src/main/res/layout/empty_state_card_view.xml, library/src/main/res/layout/empty_state_screen_view.xml, library/src/main/res/values/attrs_components.xml
Add progress button to empty state
Use this PR to solve update problem with Feedback component
* Replace Button by Progress Button in Empty State component
* Add options to Catalog
* Add update function to Feedback component
https://user-images.githubusercontent.com/42326032/232830430-3633cf3d-8c6c-4904-a37e-b395da9d9bd8.mov
=> Add loading button to empty state

library/src/main/java/com/telefonica/mistica/compose/tabs/README.md, library/src/main/java/com/telefonica/mistica/compose/tabs/Tabs.kt
Add tesTag on each tab inside Tabs.
_Provide a description of the implementation. A list of steps would be ideal._
* _Modify data class Tab_
* _Whether tabId is not null we add it to Box_
=> Add testTag to Text title of each tab

UPGRADING.md
Document the main migration catalog changes for the rest of the projects.
* Update "UPGRADING" document.
N/A
N/A
=> ANDROID-11475 Add catalog migration info

.github/workflows/import-design-tokens.yml, library/src/main/res/values-night/themes_blau_autogenerated.xml
Fix token in import design tokens github action
- It has been tested here https://github.com/Telefonica/mistica-android/actions/runs/5142621099 and it works.
- And this PR was created automatically https://github.com/Telefonica/mistica-android/pull/254
=> ANDROID-13218 Fix token

README.md, build.gradle, catalog/build.gradle, library/build.gradle
Remove move and adjust some compose versions 
* Remove BOM
No visual evidence.
=> ANDROID-13507. Remove BOM (again)

README.md
Add instructions to add a new type of token
=> Add instructions to add a new type of token

library/src/main/java/com/telefonica/mistica/compose/theme/brand/BlauBrandColorsAutogenerated.kt, library/src/main/java/com/telefonica/mistica/compose/theme/brand/MovistarBrandColorsAutogenerated.kt, library/src/main/java/com/telefonica/mistica/compose/theme/brand/O2BrandColorsAutogenerated.kt, library/src/main/java/com/telefonica/mistica/compose/theme/brand/TelefonicaBrandColorsAutogenerated.kt, library/src/main/java/com/telefonica/mistica/compose/theme/brand/VivoBrandColorsAutogenerated.kt, library/src/main/java/com/telefonica/mistica/compose/theme/brand/VivoNewBrandColorsAutogenerated.kt, library/src/main/java/com/telefonica/mistica/compose/theme/color/MisticaColorsAutogenerated.kt, library/src/main/res/drawable/stepper_progress_background.xml, library/src/main/res/values-night/themes_blau_autogenerated.xml, library/src/main/res/values-night/themes_movistar_autogenerated.xml, library/src/main/res/values-night/themes_o2_autogenerated.xml, library/src/main/res/values-night/themes_telefonica_autogenerated.xml, library/src/main/res/values-night/themes_vivoNew_autogenerated.xml, library/src/main/res/values-night/themes_vivo_autogenerated.xml, library/src/main/res/values/attrs_autogenerated.xml, library/src/main/res/values/colors_blau_autogenerated.xml, library/src/main/res/values/colors_movistar_autogenerated.xml, library/src/main/res/values/colors_o2_autogenerated.xml, library/src/main/res/values/colors_telefonica_autogenerated.xml, library/src/main/res/values/colors_vivoNew_autogenerated.xml, library/src/main/res/values/colors_vivo_autogenerated.xml, library/src/main/res/values/themes_blau_autogenerated.xml, library/src/main/res/values/themes_movistar_autogenerated.xml, library/src/main/res/values/themes_o2_autogenerated.xml, library/src/main/res/values/themes_telefonica_autogenerated.xml, library/src/main/res/values/themes_vivoNew_autogenerated.xml, library/src/main/res/values/themes_vivo_autogenerated.xml
[OBVIVO-2243](https://jira.tid.es/browse/OBVIVO-2243)
[OBVIVO-2271](https://jira.tid.es/browse/OBVIVO-2271)
[ANDROID-14159](https://jira.tid.es/browse/ANDROID-14159)
=> Update design tokens

library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
Add test tag to callout compose item
* Create test tag object according to ids defined in figma: https://www.figma.com/file/LzhzNPzE8nY9d7Yvo10d5d/branch/ZlA7HAgRWKVh22jkATo3AM/%F0%9F%94%B8-Callout-Component-Specs?type=design&mode=design&t=pqvpsjNeh65C6BQr-0
* Add test tag to callout sub items
=> Add test tag to callout compose item

UPGRADING.md
Add forgotten documentation on #331 
* _Add documentation_
=> ADD- doc to 11.1.1 update #ANDROID-14496

library/src/main/java/com/telefonica/mistica/compose/tabs/Tabs.kt
Avoid duplicated tags in Compose Tab element
This error was caused by SubcomposeLayout. During measurement phase composables are created but they are not deleted when the measurement is finished.
The solution applied was to not set tags during measurement of composition. There are still duplicated elements but only those that are visible have a tag
=> ANDROID-13760 Avoid duplicated tags in Compose Tab element

.github/PULL_REQUEST_TEMPLATE.md
[ANDROID-15141](https://jira.tid.es/browse/ANDROID-15141)
Add new accessibility check in PR template.
* Add new check in PULL_REQUEST_TEMPLATE.md file.
Minor change. Check code changes.
=> ANDROID-15141 - New accessibility check

build.gradle, publish_maven_central.gradle
Migrate to CentralPortal platform.
* Update [gradle-nexus/publish-plugin](https://github.com/gradle-nexus/publish-plugin) to 2.0.0.
=> ANDROID-16181 OSSRH to CentralPortal

.github/workflows/release.yml
Checkout main branch to add new version on it
We need to checkout a branch before committing on it: https://github.com/Telefonica/mistica-android/actions/runs/15869763307/job/44743482568#step:10:258
To be tested generating a new release
=> ANDROID-16374 fix commit to main

.github/workflows/tests.yml, build.gradle, catalog/build.gradle, catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/CalloutsCatalogFragment.kt, gradle/wrapper/gradle-wrapper.properties, library-test-utils/build.gradle, library/build.gradle, library/src/main/java/com/telefonica/mistica/card/CardActionsView.kt, library/src/main/java/com/telefonica/mistica/compose/composeview/AbstractMisticaComposeView.kt, library/src/main/java/com/telefonica/mistica/header/HeaderView.kt, library/src/main/java/com/telefonica/mistica/highlightedcard/HighlightedCardView.kt, library/src/main/java/com/telefonica/mistica/list/ListRowView.kt, library/src/main/java/com/telefonica/mistica/list/decoration/divider/DividerItemDecoration.kt, library/src/main/java/com/telefonica/mistica/util/Base64DataUrlFetcher.kt
https://jira.tid.es/browse/ANDROID-16481
Update Kotlin and use integrated compose compiler and some versions that were not unified
Tested in catalog
=> ANDROID-16481 Update Kotlin
