- .github/workflows/promote_release.yml
- .github/workflows/release.yml
- build.gradle
- catalog/build.gradle
- library/build.gradle
- mavencentral.gradle
Publish releases in MavenCentral.
The steps to publish are going to be:
1. Generate a release with the github action.
2. The result will be a release draft, the user will need to go there and publish the draft.
3. At that moment, the artifact, which is in a staging state in mavenCentral will be published.
There are two github actions, one to publish to staging and the second one to promote the staging repository.
The first one: release.yml sends the library and the catalog to mavenCentral.
And then the second one, closes & promotes the currently opened staging repository
> Publish in MavenCentral

- library/src/main/res/values/styles_tab_layout.xml
Current tab indicator color is colorControlActivated, it should be colorControlActive
> ANDROID-9581 fix tab indicator color

- library/src/main/res/values-en/strings_load_error_feedback.xml
- library/src/main/res/values-pt/strings_load_error_feedback.xml
Fix https://jira.tid.es/browse/ANDROID-9679, where a copy is not properly translated to pt-BR
* Just fix the translations
- No need to update docs
- No need to test with dark mode or API 21
Before | After
--- | ---
> ANDROID-9679 Fix translations

- .github/PULL_REQUEST_TEMPLATE.md
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/fragment/ListsCatalogFragment.kt
- library/src/main/java/com/telefonica/mistica/list/ListRowView.kt
Fix this bug https://jira.tid.es/browse/ANDROID-9693 where `ListRowView` text have a wrong color on devices with API < 23.
There are actually 2 bugs here:
* For API < 23 the color is retrieved without taking the theme into account.
* We're applying primary color to subtitle and description, and it should be secondary [according to the docs](https://zpl.io/25LQ8ne).
`ContextCompat.getColor` ignores theme for API < 23, also for `ColorStateList` (selectors). So we need to find a different way to set the `ColorStateList` colors into the `TextViews`.
* Instead of retrieving the `ColorStateList` from resources, we create a new one for each case (thus duplicating those colors, now we have them defined in xml resources and Kotlin code. I'm open to better solutions).
* Apply primary or primary …
> ANDROID-9693 Fix ListRowView text color on API < 23

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/fragment/TabsCatalogFragment.kt
- library/src/main/java/com/telefonica/mistica/button/ProgressButton.kt
- library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
- library/src/main/java/com/telefonica/mistica/card/CardView.kt
- library/src/main/java/com/telefonica/mistica/card/datacard/DataCardView.kt
- library/src/main/java/com/telefonica/mistica/card/mediacard/MediaCardView.kt
- library/src/main/java/com/telefonica/mistica/contentindicator/ScrollContentIndicator.kt
- library/src/main/java/com/telefonica/mistica/emptystate/card/EmptyStateCardView.kt
- library/src/main/java/com/telefonica/mistica/emptystate/screen/EmptyStateScreenView.kt
- library/src/main/java/com/telefonica/mistica/highlightedcard/HighlightedCardView.kt
- library/src/main/java/com/telefonica/mistica/list/ListRowView.kt
- library/src/main/java/com/telefonica/mistica/list/decoration/divider/DividerItemDecoration.kt
Programatic drawable load should be done with `AppCompatResources`, in order to support new vector drawables attributes on old android api versions. This avoids possible crashes on older api versions.
For example, Empty states illustrations loads are crashing without this.
From [link](https://stackoverflow.com/a/43005362):
```
#1 Do you have to support API 4, 5, or 6?
Yes: No choice but to use ResourcesCompat or ContextCompat.
No: Keep going to #2.
#2 Do you absolutely need to supply a custom Theme?
Yes: No choice but to use ResourcesCompat
No: Use AppCompatResources
```
* Just change all programatic drawable loads to use `AppCompatResources`
> ANDROID-9856 Make mistica drawable loads to use AppCompatResources

- library/build.gradle
The goal of this change is to fix a problem when two libraries with the same module name are included in the same project. The file `META-INF/library_release.kotlin_module` has the same name in both cases and it throws an error.
* Just specifying a name to the library module `com.telefonica.mistica` in this case to avoid duplicates.
> ANDROID-9906 Update library module name

- library-compose/src/main/java/com/telefonica/mistica/compose/theme/MisticaTheme.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/theme/text/MisticaTypography.kt
Just set default text color on compose themes, so brand and dark mode config changes modifies it.
* Just configure base text style with a default color
> Set default text color for compose themes

- app/src/main/AndroidManifest.xml
- catalog/lint.xml
- catalog/src/main/AndroidManifest.xml
- library/lint.xml
- library/src/main/AndroidManifest.xml
- library/src/main/res/layout/list_row_item.xml
We're exporting `supportRtls = false` attribute in Mística. This ticket fixes the errors that doesn't enable us to set it to true and then removes it from the manifest.
I've fixed the lint error (only one) so we can support Rtls (according to Lint).
Then I've excluded the supportRtls tag from the library manifest by ignoring the lint rule that checks it.
The rule was forcing me to put it in the manifest:
```
/Users/gmerino/Workspace/tuenti/mistica-android/library/src/main/AndroidManifest.xml: Error: The project references RTL attributes, but does not explicitly enable or disable RTL support with android:supportsRtl in the manifest [RtlEnabled]
```
- Having blue ball should be enough
- Tested lists manually
> ANDROID-10054 - Deleting app tag

- mavencentral.gradle
If you check https://search.maven.org/artifact/com.telefonica/mistica-compose/3.2.0/aar
you'll see 
We should use "mistica" instead
> ANDROID-10116 - Remove library dependency from the pom.xml and adding Mistica instead

- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Feedbacks.kt
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/activity/FeedbackScreenCatalogActivity.kt
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/fragment/FeedbackScreenCatalogFragment.kt
- catalog/src/main/res/layout/screen_fragment_feedback_catalog.xml
- library-compose/src/main/java/com/telefonica/mistica/compose/feedback/Feedback.kt
- library/src/main/java/com/telefonica/mistica/feedback/screen/README.md
- library/src/main/java/com/telefonica/mistica/feedback/screen/view/FeedbackScreenView.kt
- library/src/main/res/layout/screen_feedback.xml
- library/src/main/res/values/attrs_components.xml
Add the possibility of including an error reference text in Error Feedbacks.
Check ticket for details -> ANDROID-10046
As talked with iOS, component will accept whole field text, instead of just the error reference, so, this way mistica does not need to hold any translation/default token.
* Include a new field in the feedback component that allows specifying a string for this
* Adapt compose function with this new parameter
> ANDROID-10046 Error reference in Feedbacks

- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Lists.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/tag/Tag.kt
This is just kind of a PoC, I hadn't time to migrate other usages, but I think it can be a good approach to restrict that some parts of bigger components that are defined as composable to accept only the components we want to add.
Limit list row headline to only accept Tags
* Expose a class with the same name as the composable function: Tag
* That class will have a build method that creates the composable
* Restrict the ListRowItem parameter to only accept Tag (the class)
https://user-images.githubusercontent.com/4595241/144257978-1e33b37d-fd6e-4f48-b86e-ae2aa5e95e71.mp4
> ANDROID-10148 PoC of how to restrict @Composable functions to only allow certain components

- app/build.gradle
ANDROID-10257 The appcenter plugin has a bug that crashes the upload when attempting to upload the mapping file if it doesn't exist
In Mística we will never have mapping file. So I'm setting the upload mapping file flag to false
> ANDROID-10257 - Not uploading mappings (they doesn't exist in debug)

- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Lists.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
Fix ListRowItem vertical padding and title style (only in Compose version of the component)
- Row title from light to regular
- Space between rows should be 16dp, when each row sum 8dp
- Removed dividers from catalog in order to be aligned with non-composable catalog where there aren't dividers
| Before | After |
| ------ | ------ |
| <img width="373" alt="Captura de pantalla 2022-01-19 a las 16 27 29" src="https://user-images.githubusercontent.com/47142570/150161835-3ade0509-1583-485f-a6f1-799388c843b5.png"> | <img width="376" alt="Captura de pantalla 2022-01-19 a las 16 20 09" src="https://user-images.githubusercontent.com/47142570/150161718-871dc975-9b2f-46a5-95d4-69dc06105af2.png"> |
> ANDROID-10252 [Compose] Fix ListRowItem vertical padding and title style

- library-compose/src/main/java/com/telefonica/mistica/compose/card/Card.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/carousel/Carousel.kt
ANDROID-10301 The link button is not shown if the action is not present
Replacing and `&&` by an `||` and adjusting the padding
> ANDROID-10301 Fix link button in cards

- library-compose/src/main/java/com/telefonica/mistica/compose/card/Card.kt
Non-composable DataCard don't force caps on its subtitle so we shouldn't be doing the same in the Compose version.
Remove call to `uppercase` over DataCard subtitle
> ANDROID-10345 Do not capitalize data card subtitle in compose

- library-compose/src/main/java/com/telefonica/mistica/compose/card/datacard/IconPainter.kt
DataCard component in Compose library allows to set an icon using a drawable resource Id but it is not possible to customize the resulting icon shown.
I have added two extra params with default values so the change is not breaking:
- `iconTint: Color? = null`
- `backgroundColor: Color = MisticaTheme.color.neutralLow` (current value for the icon background)
This isn't a change on the specification of DataCard but an internal change required by us so we can have moreo control over how its icon is drawn (without having to have multiple assets instead of just one but tinted multiple times)
The following screenshot shows a DataCard with an icon tinted and a background with a custom color as well
> ANDROID-10348 Allow customization in Compose DataCard icon

- library-compose/src/main/java/com/telefonica/mistica/compose/card/Card.kt
- library/src/main/res/layout/card_content_view.xml
Let 16dp from TagView not taking into account whether view is below.
Changing margins
> ANDROID-10304 Fix margin Tag to any view in Cards

- library-compose/src/main/java/com/telefonica/mistica/compose/tag/Tag.kt
- library/src/main/java/com/telefonica/mistica/tag/TagView.kt
Due to this [ticket](https://jira.tid.es/browse/TGT-548), it has been detected that it was not wanted to force a capitalization of the first character and leave the rest in lowercase. The propose is leave server to customise string format.
Targeting Ticket: [TGT-548](https://jira.tid.es/browse/TGT-548)
Android Ticket: [ANDROID-10428](https://jira.tid.es/browse/ANDROID-10428)
Removing this feature.
[Screenshot](https://user-images.githubusercontent.com/8106237/155361856-9b04cc69-2663-4ce2-be8f-f0b9e81080e0.png)
> ANDROID-10428 Remove capitalization on Tags

- library-compose/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
There is no minimum height. Setting one.
https://app.zeplin.io/project/5d653c69f828bf7299c551c1/screen/5e9d50079630597dd4731f3d
Just setting the min height
https://user-images.githubusercontent.com/4595241/155322587-19061450-0ed9-4232-9cfc-01ba7adee9d4.mp4
> ANDROID-10425 - Set min height in lists

- library-compose/src/main/java/com/telefonica/mistica/compose/button/Button.kt
Allow enabling/disabling Composable Button
Adding a `enabled` param to the `Button` composable that is used internally to update the state of the wrapped `AndroidView` in its update function.
| Disabled | Enabled |
| ---- | ---- |
| ![Captura de pantalla 2022-03-17 a las 17 24 42](https://user-images.githubusercontent.com/47142570/158846984-44e2bc69-b24f-4442-8667-0a2bf9e59201.png) | ![Captura de pantalla 2022-03-17 a las 17 25 21](https://user-images.githubusercontent.com/47142570/158847139-47b1a424-5a29-4275-b703-38737a7725c9.png) |
> Allow enabling/disabling Composable Button

- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Inputs.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/input/EmailInput.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/input/PhoneInput.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/input/TextInput.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/input/TextInputImpl.kt
In some cases we will want to add some visual effects/format to a text input. I'm exposing the same `VisualTransformation` param that built-in `TextField` expose
- Propagate `VisualTransformation` from `TextField` to `PhoneInput`, `EmailInput` and `TextInput` and setting `VisualTransformation.None`. as the default value (just like in `TextField`).
- Add catalog example
https://user-images.githubusercontent.com/47142570/159954971-13203686-688a-4f23-a49a-a09b23970ccd.mov
> Add visual transformation param to Text, Email and Phone inputs

- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/CatalogMainActivity.kt
- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Buttons.kt
- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Steppers.kt
- catalog-compose/src/main/res/drawable/ic_stepper.xml
- library-compose/README.md
- library-compose/src/main/java/com/telefonica/mistica/compose/stepper/IndeterminateStepper.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/stepper/README.md
- library/src/main/java/com/telefonica/mistica/stepper/DeterminateStepperView.kt
- library/src/main/java/com/telefonica/mistica/stepper/IndeterminateStepperView.kt
Migrate Stepper to compose, but for now only `IndeterminateStepperView` view since it is needed by another app.
- Wrap `IndeterminateStepperView` into `IndeterminateStepper`
- Add param `animate: Boolean = true` to `IndeterminateStepperView::setProgress` method because there are some places where animation needs to be explicitly disabled
https://user-images.githubusercontent.com/47142570/160644415-5d879efd-09e4-45de-81d2-97ed609520ad.mov
> Wrap IndterminateStepperView into AndroidView composable

- library-compose/src/main/java/com/telefonica/mistica/compose/feedback/Feedback.kt
`onBackPressed` param from `Feedback` composable component should be optional so the back event is not overridden when needed.
- Make `onBackPressed` nullable with a default `null` value and only explicitly handle back event when it is present.
- Also add `null` default values to second button text and its click listener
> ANDROID-10695 Make Feedback onBackpressed param optional

- build.gradle
- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/CatalogMainActivity.kt
- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Tags.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/badge/Badge.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/shape/Chevron.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/tag/Tag.kt
_Add test tags for elements in lists component. With last version of jetpack-compose testTags are mapped as resource-ids._
_Provide a description of the implementation. A list of steps would be ideal._
* Update compose version to 1.2.0-beta02.
* Update kotlin version to 1.6.21. (Move GridCells and LazyVerticalGrid to grid subpackage)
* Add test tags.
> NOV-232171: Add test tags in ListRowItem

- library-compose/src/main/java/com/telefonica/mistica/compose/theme/MisticaTheme.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/Brand.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/MovistarBrand.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/theme/text/MisticaTypography.kt
- library/src/main/res/values/attrs_fonts.xml
- library/src/main/res/values/styles_fonts.xml
- library/src/main/res/values/themes.xml
- library/src/main/res/values/themes_movistar.xml
Presets from 5 to 8 are now Medium and not Light only in Movistar
- XML style presets: Create four new attributes to be referenced from each preset definition and set light as their default value in main base them and override them to Medium only in Movistar
- Compose typography presets: parametrize buildPresetX methods from `MisticaTypography` class and add `presetXFontWeight` properties to `Brand` interface with Light as default value and override them only in Movistar
| compose movistar | compose other brand |
| ---- | ---- |
|![Captura de pantalla 2022-06-16 a las 10 12 33](https://user-images.githubusercontent.com/47142570/174024797-59630ebf-1d50-46d1-bd98-9f80bb3cfe48.png)|![Captura de pantalla 2022-06-16 a las 10 12 48](https://user-images.githubusercontent.com/47142570/174024825-42 …
> Movistar new presets

- library-compose/src/main/java/com/telefonica/mistica/compose/card/Card.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/input/TextInputImpl.kt
- library-compose/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
- library/src/main/java/com/telefonica/mistica/emptystate/card/EmptyStateCardView.kt
- library/src/main/res/drawable/bg_callout.xml
- library/src/main/res/drawable/bg_callout_inverse.xml
- library/src/main/res/drawable/bg_textinputedittext.xml
- library/src/main/res/drawable/boxed_list_row_background.xml
- library/src/main/res/layout/screen_feedback.xml
- library/src/main/res/values/dimens_callout.xml
- library/src/main/res/values/dimens_card_view.xml
- library/src/main/res/values/dimens_popover.xml
- library/src/main/res/values/list_row_corner_radius.xml
As part of Mistica Evolution, there have been some changes related to corner radius and other small changes
Change (compose and xml) the corner radius here and there from 4px to 8px (actually dp on Android) in the following components:
- Cards (data and media)
- Callout
- Popover
- Boxed list items
- Empty state card
- Forms
Other fixes:
- Change feedback subtitle style from light to regular
- Empty state card icon size from 64 to 48
| component | before | after |
| ---- | ---- | ---- |
| media card | ![Captura de pantalla 2022-06-21 a las 10 54 06](https://user-images.githubusercontent.com/47142570/174759490-ee50463b-c403-40bc-9899-2db2df95e4d0.png)| ![Captura de pantalla 2022-06-21 a las 10 57 34](https://user-images.githubusercontent.com/47142570/174760246-35d88bc7-0857-463d-a098-ea645e …
> ANDROID-10672 New corner radius

- library/src/main/res/layout/empty_state_screen_view.xml
- library/src/main/res/layout/screen_feedback.xml
Update Feedback and Empty state subtitles style to preset3/regular
Set `AppTheme.TextAppearance.Preset3` to subtitles from `FeedbackScreenView` and `EmptyStateScreenView`
Compose version of these components are just wrappers over xml ones, so they are updated for free
**Note**: Note that Feedback subtitle was already Preset4/regular from the recent changes, that's why the visual changes are more subtle than empty state ones
| component | Before | after |
| ---- | ---- | ---- |
| Feedback | ![Captura de pantalla 2022-07-01 a las 14 27 05](https://user-images.githubusercontent.com/47142570/176894239-48c821a0-0b29-4575-9cf3-fe8951a6bd28.png) | ![Captura de pantalla 2022-07-01 a las 14 23 05](https://user-images.githubusercontent.com/47142570/176893613-d2efcddd-6765-42f8-b1c3-c87a70293f77.png) …
> ANDROID-10672 Update feedback and empty state subtitle style

- library-compose/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
- library/src/main/res/drawable/boxed_inverse_list_row_background.xml
Corner radius on  boxed list row items should be set to 8dp, it was changed for its standard version but not for its "inverse" version.
4dp to 8dp on boxed inverse list row item
XML
Compose
> ANDROID-10672 Fix corner radius in boxed inverse list row item

- library/src/main/res/values/styles_forms.xml
Ticket -> [ANDROID-11208](https://jira.tid.es/browse/ANDROID-11208)
Fix TextInputLayout errors detected during Latch v3 development.
Basically:
- Hint and Error indicators should use preset1 and shoud recognize any overriden font
- Big hint text should use ?colorTextSecondary as mistica specifies
This has not been detected in the past because material color used matches our textSecondary, and fields were never used with a different typography than roboto.
* Add preset1 configuration to hint and error styles (Needs to be copied as we can't use multiple inheritance)
* Configure hint text color as ?colorTextSecondary
<table>
<tbody>
<tr>
<td>Before</td>
<td>After</td>
</td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/5360064/196740471-a93ca3b3-e8c7-425c-bd4a-0a50aa8cc54 …
> ANDROID-11208 Fix TextInputLayout mistica themes

- app/build.gradle
- build.gradle
- catalog-compose/build.gradle
- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Lists.kt
- catalog/build.gradle
- library-compose/build.gradle
- library-compose/src/main/java/com/telefonica/mistica/compose/card/datacard/IconPainter.kt
- library/build.gradle
Update coil version as it depends on a version of okhttp that has a vulnerabilty.
Update coil version:The minimum supported API is now 21.
No breaking changes apply: https://coil-kt.github.io/coil/upgrading/
Coil 2.2.0 requires update compile sdk to 32 as it depends on compose 1.2.1: https://coil-kt.github.io/coil/changelog/ so version 2.1.0 has been applied
Tested using catalog app
After reviewing further version updates, we are blocked by current sdk version. I have created a newer task to increase versions and use a compose a stable version: https://jira.tid.es/browse/ANDROID-11299
kotlin-extensions are not used in the project
> ANDROID-11216 update coil version

- library/src/main/res/values-night/themes_blau.xml
- library/src/main/res/values-night/themes_movistar.xml
- library/src/main/res/values-night/themes_o2.xml
- library/src/main/res/values-night/themes_o2_classic.xml
- library/src/main/res/values-night/themes_telefonica.xml
- library/src/main/res/values-night/themes_vivo.xml
- library/src/main/res/values/attrs_colors.xml
- library/src/main/res/values/themes_blau.xml
- library/src/main/res/values/themes_movistar.xml
- library/src/main/res/values/themes_o2.xml
- library/src/main/res/values/themes_o2_classic.xml
- library/src/main/res/values/themes_telefonica.xml
- library/src/main/res/values/themes_vivo.xml
Add a new color `colorCustomTabsBackground` to all brands following the changes of this PR https://github.com/Telefonica/mistica-design/pull/892.
| Brand        | Screenshots           | Dark  Screenshots         |
| ------------- |-------------|-------------|
| Vivo | <img src="https://user-images.githubusercontent.com/2582348/202395809-52ead674-5950-4bbb-a7c7-154d07f2533d.png" alt="drawing" width="200"/> | <img src="https://user-images.githubusercontent.com/2582348/202395824-091a75b5-60f4-4f4f-8296-5fe4d0356b87.png" alt="drawing" width="200"/> |
| Movistar | <img src="https://user-images.githubusercontent.com/2582348/202399451-9676920a-6e4a-4671-9fb3-ee69fb9d25c2.png" alt="drawing" width="200"/> | <img src="https://user-images.githubusercontent.com/2582348/202399440-cde00850-1f34-45de-88 …
> ANDROID-11320 Add colorCustomTabsBackground to all brands

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/fragment/SnackBarCatalogFragment.kt
- catalog/src/main/res/layout/screen_snackbar_catalog.xml
- library/src/main/java/com/telefonica/mistica/feedback/README.md
- library/src/main/java/com/telefonica/mistica/feedback/SnackbarBuilder.kt
Allow snackbar of 5 or 10 seconds if it does not have an action
* Add component property
* Add catalog option
It can be tested in the dialog app
[mistica_10_result.webm](https://user-images.githubusercontent.com/36664452/203350341-802e3c61-a674-46e1-9229-6fc3bccc295f.webm)
> ANDROID-11369 snackbar allow 10 seconds

- app/build.gradle
Fix catalog app version code
After January 31st, the version code is causing an error:
Cause: android.defaultConfig.versionCode is set to -2145093261, but it should be a positive integer.
See https://developer.android.com/studio/publish/versioning#appversioning for more information.
Use time in milliseconds
> fix: catalog app version code

- library/src/main/java/com/telefonica/mistica/compose/theme/text/MisticaTypography.kt
- library/src/main/res/values/colors_telefonica.xml
- library/src/main/res/values/styles_fonts.xml
_Provide a description of the overall goal. The description in the Jira ticket may help._
We update the sizes of typography in text-presets for all brands
text-preset-5 from 22 to 20
> Preset sizes changes

- library/src/main/java/com/telefonica/mistica/compose/theme/brand/BlauBrand.kt
- library/src/main/res/values-night/themes_blau.xml
Fix Blau link inverse color in dark mode as specified in https://github.com/Telefonica/mistica-design/blob/production/tokens/blau.json#L690.
Override `colortextLinkInverse` constant with purple_30 color in dark mode.
| Type | Light | Dark |
| --- | --- | --- |
| Compose | <img width="271" alt="Captura de Pantalla 2023-02-22 a las 12 33 04" src="https://user-images.githubusercontent.com/47142570/220608401-af5e5bc1-0dd5-4938-b500-a9ec0dd575fc.png">|<img width="307" alt="Captura de Pantalla 2023-02-22 a las 12 33 24" src="https://user-images.githubusercontent.com/47142570/220608462-e340dcd0-0348-4b72-9612-fe56119cd56e.png">|
| XML |<img width="356" alt="Captura de Pantalla 2023-02-22 a las 12 32 39" src="https://user-images.githubusercontent.com/47142570/220608312-01d333e8-393a-4314-993c-1127 …
> ANDROID-11693 Fix Blau link inverse color in dark mode

- README.md
- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/CatalogMainActivity.kt
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/CatalogMainActivity.kt
- library/src/main/java/com/telefonica/mistica/compose/README.md
- library/src/main/java/com/telefonica/mistica/compose/composeview/AbstractMisticaComposeView.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/MovistarBrand.kt
- library/src/main/res/values-night/themes_movistar.xml
- library/src/main/res/values/attrs_components.xml
- library/src/main/res/values/colors_movistar.xml
- library/src/main/res/values/themes_movistar.xml
Remove Movistar Prominent Theme
Remove Prominent Theme and related colors and references in the Catalog
> ANDROID-11721 remove prominent style

- .github/workflows/catalog.yml
- .github/workflows/debug_catalog.yml
- app/appcenter_projects.properties
- app/build.gradle
Generate debug catalog when the PR is created or a new commit is pushed
* Parameterize app center app name in `build.gradle` to be able to select the project.
* Create new Github Action `debug_catalog` to generate and upload the catalog automatically.
> ANDROID-11728 Generate catalog when the PR is created

- .github/workflows/debug_catalog.yml
Fix debug catalog posted link. We were not posting the link of the last generated version.
To fix it I've changed the API that we were using. Now we do two requests, in the first one we get the last uploaded version ID and in the second one we get the link to download that version.
> ANDROID-11767 Fix debug catalog posted link

- library/src/main/java/com/telefonica/mistica/compose/theme/brand/BlauBrand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/O2Brand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/TelefonicaBrand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/VivoBrand.kt
- library/src/main/res/values/colors_telefonica.xml
- library/src/main/res/values/themes_blau.xml
- library/src/main/res/values/themes_o2.xml
- library/src/main/res/values/themes_telefonica.xml
- library/src/main/res/values/themes_vivo.xml
[ANDROID-11659](https://jira.tid.es/browse/ANDROID-11659)
Update textSecondaryInverse (light mode) for all brands. Requested by design.
Movistar: movistarBlue10 (this one was OK)
Vivo: vivoPurpleLight20
O2: o2BluePrimary15
Blau: blauBluePrimary20
Telefónica: telefonicaBlue10
Updating the TextSecondaryInverse colour of all brands in compose as in xml.
> ANDROID-11659 Update TextSecondaryInverse colours for all brands (light mode)

- .github/workflows/debug_catalog.yml
Add public appcenter link to be able to download the testing catalog if the download link has expired.
You can see the result in the comment.
> ANDROID-11911 Add public appcenter link

- build.gradle
- catalog-compose/build.gradle
- library/build.gradle
After having introduced Compose BOM, we are no longer able to import this library on other repositories. We are reverting the commit in which that BOM was included and investigating the issue in the meantime.
Revert https://github.com/Telefonica/mistica-android/commit/87a39686dca4dc448cc447cdb91572655e5ef93e
- Published to maven local and tested that it can be included on any project
> Revert Compose BOM usage

- catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/Inputs.kt
- library/src/main/java/com/telefonica/mistica/compose/input/CharsCounter.kt
- library/src/main/java/com/telefonica/mistica/compose/input/README.md
- library/src/main/java/com/telefonica/mistica/compose/input/TextAreaInput.kt
- library/src/main/java/com/telefonica/mistica/compose/input/TextInputImpl.kt
[ANDROID-11916](https://jira.tid.es/browse/ANDROID-11916)
Add a TextArea component as the one there is in the gallery that it's using traditional views.
- Created new TextAreaInput composable.
- Created new CharsCounter composable.
- Updated TextInputImpl so that it allows multiline when isTextArea
- Added underlineEnd slot to TextInputImpl so we can pass a CharsCounter when it's a textarea, this would allow any input to have CharsCounter or another composable on the bottomright if needed.
https://user-images.githubusercontent.com/13270085/230917350-d1325bd9-ea48-46ae-af3e-6bb76d0c1e15.mov
> ANDROID-11916 Text Area in Compose

- build.gradle
- catalog-compose/build.gradle
- library/build.gradle
When Compose BoM was included on Mistica (Version 7.3.1). The compilation failed on every project that didn't use Compose and Mistica dependency is added. This is the error:
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all files for configuration ':app:movistarESDebugCompileClasspath'.
> Could not find androidx.compose.ui:ui-tooling-preview:.
Required by:
project :app > com.telefonica:mistica:7.3.1
```
The BoM usage was temporarily reverted in #228, so I reverted the revert
I haven't find the real reason behind this but setting the explicit version on Mistica for that package does the trick. It allows the version to be included in the `pom.xml` published to Maven. 
On the other hand, we haven't seen the error occur for other packages from the …
> Fix compose bom releases

- README.md
- build.gradle
- library/build.gradle
- library/src/main/java/com/telefonica/mistica/compose/card/highlightedcard/HighLightedCard.kt
- library/src/main/java/com/telefonica/mistica/compose/card/highlightedcard/README.md
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/BlauBrand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/MovistarBrand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/O2Brand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/TelefonicaBrand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/VivoBrand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/color/MisticaColors.kt
[Task](https://jira.tid.es/browse/ANDROID-11507)
Migrate XML HighLightedCard implementation to Compose
Added new HighLightedCard composable with all settings posibilites made like other compose implementations (settings data classes to minifly the number of parameters.
> Migrate HighLighted Cards to Compose ANDROID-11507

- .github/workflows/tests.yml
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Lists.kt
- library/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
Include the custom and optional bottom fragment in the ListRowItem according to the specs
:warning: By now it is only implemented in the Compose version of the component. It will be implemented on demand for the xml version. :warning:
Add a new composable called `bottom` as param to the ListRowItem composable.
Other changes in this PR:
- Set `height(IntrinsicSize.Min)` to the whole row so `trailing` content can use `fillMaxHeight`
- Fix background color for boxed rows according to the specs (`backgroundContainer `)
> ANDROID-11435 Allow custom bottom section in ListRowItem

- .github/workflows/catalog.yml
- .github/workflows/debug_catalog.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/tests.yml
- Snapshot workflow is not working right now because there is no such task as `publishNoopPublicationToSonatypeRepository`. I'm fixing it.
- I'm also replacing `self-hosted-novum` runner with `ubuntu-latest` in some of the workflows because we actually don't need `novum_android_api31` docker image at all.
- Use the same command as in `release.yml` workflow but with `SNAPSHOT_VERSION` param
- Remove every unneeded usage of `self-hosted-novum` and use `ubuntu-latest` instead
- Remove every unneeded usage of `novum_android_api31` docker image
- No need to be reviewed by design team
- Checked that `tests.yml` and `debug_catalog.yml` are executed successfully
> Fix generate snapshot workflow and get rid of self hosted runners

- build.gradle
- catalog/build.gradle
- library/build.gradle
Remove Compose BoM since it is right now giving us some dependency resolution problems at the time of importing Mistica in other projects (missing dependencies, not found classes after on release builds, etc).
Revert the commit 7c9b20518bae233e766e876ac77a0003cd8ed5cd where it was introduced and solve conflicts since then
> Remove compose bom

- library/src/main/java/com/telefonica/mistica/compose/input/TextInputImpl.kt
- library/src/main/java/com/telefonica/mistica/compose/input/TextInputTestTags.kt
- library/src/main/java/com/telefonica/mistica/compose/ui/ModifierExt.kt
The label of an compose TextInput has a wrong position when the input field has a fixed height 
```kotlin
TextInput(
modifier = modifier
.fillMaxWidth()
.size(84.dp) // <-- Fixed height
,
value = text,
onValueChange = {
text = it
},
label = "Type Something",
enabled = enabled,
)
```
The label is placed on the very top of the composable:
Remove aparenttly unneeded Box and alignment for given label
> ANDROID-13350 Wrong TextInput label position when fixed height

- library/src/main/java/com/telefonica/mistica/compose/input/PasswordInput.kt
- library/src/main/java/com/telefonica/mistica/compose/input/TextInputTestTags.kt
Expose the constant used as the testTag for the "show/hide password" icon button
Make it public
> Expose password toggle test tag

- library/src/main/res/values/themes_vivo.xml
The feedback error icon for Vivo is not defined in theme_vivo as it is already for other brand themes.
Define the correct value for "feedbackScreenErrorAnimation" attribute, which is "@raw/feedback_error".
I've done the same for "feedbackScreenInfoIcon" icon attribute with the value "@drawable/feedback_info".
It is not being reproduced with the existing Catalog probably because Vivo is not the only theme used in runtime and a previous value may remain for this attribute.
| Error | Info |
| --- | --- |
|![Captura de Pantalla 2023-06-07 a las 16 30 29](https://github.com/Telefonica/mistica-android/assets/47142570/b1bd5d6a-5651-4a4c-94ea-3ccf86143ab5)|![Captura de Pantalla 2023-06-07 a las 16 31 34](https://github.com/Telefonica/mistica-android/assets/47142570/999c7f16-e8e0-463e-8c9d-4d978eb6 …
> ANDROID-13391 Define error feedback icon resource for vivo

- tokens/src/main/java/com/telefonica/mistica/tokens/xml/GenerateXMLFiles.kt
Fix dark mode tokens with alpha
Add alpha check in dark theme files generation method.
Evidence: https://github.com/Telefonica/mistica-android/pull/269 (Updated)
> ANDROID-13440 Fix dark mode tokens with alpha

- .github/workflows/import-design-tokens.yml
Add workflow trigger author as assignee to "update design tokens" PRs
Use `assignees` field from the action we are already using to create the PR (https://github.com/peter-evans/create-pull-request)
> ANDROID-13505 Add assignees to update design tokens PRs

- .github/workflows/debug_catalog.yml
Cancel ongoing debug_catalog.yml jobs
Add cancel-in-progress flag to debug_catalog.yml worflow and also avoid its execution when we have modified files that matches the following regex:
- `**.md`
- `doc/**`
- `tokens/**`
- `.github/**`
No checks needed
- Debug catalog action was not triggered when a file inside the discarded ones is modified
> Cancel ongoing debug_catalog.yml jobs

- .github/workflows/debug_catalog.yml
Now that AppCenter supports public URLs that point to a specific version, we don't need anymore the logic to obtain the private URL that expires.
- I've tested locally using ACT:
```
[Generate debug catalog app/debug-catalog]   ✅  Success - Main Get version URL
[Generate debug catalog app/debug-catalog]   ⚙  ::set-output:: appcenter_url=https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-catalog/distribution_groups/public/releases/259
```
> Post catalog public URL with specific version

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/ListsCatalogFragment.kt
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Lists.kt
- catalog/src/main/res/drawable/ic_error.xml
- library/src/main/java/com/telefonica/mistica/compose/list/ListRowIcon.kt
- library/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
- library/src/main/java/com/telefonica/mistica/compose/list/README.md
- library/src/main/java/com/telefonica/mistica/list/ListRowView.kt
- library/src/main/java/com/telefonica/mistica/list/README.md
- library/src/main/res/layout/list_row_item.xml
- library/src/main/res/values/attrs_components.xml
- library/src/main/res/values/styles_images.xml
Update list row icon to don't let developers add any kind of views.
Add new list spec
* load url image
* asset image with aspect ratio 1:1
* asset image with aspect ratio 16:9
* asset image with aspect ratio 7:10
* Update compose views 
* * Create new sealed class with all image types
* * Create draw function foreach new image types
* Update xml views
* * Add new aspect ratio images to current implementation
* Update Catalog
https://github.com/Telefonica/mistica-android/assets/42326032/7d0865d1-08a8-4c23-b3c5-aeb37e631fc1
> Android-13531 Update list row icon

- library/src/main/java/com/telefonica/mistica/compose/feedback/error/LoadErrorFeedback.kt
- library/src/main/java/com/telefonica/mistica/feedback/SnackbarBuilder.kt
- library/src/main/res/layout/load_error_feedback.xml
Use "tokenized" presets for Snackbar and LoadErrorFeedback components.
- Use "PresetLink" for Snackbar action
- Use "PresetCardTitle" for LoadErrorFeedback title component
> ANDROID-13561 Tokenize SnackBar and LoadErrorFeedback

- library/src/main/java/com/telefonica/mistica/button/Button.kt
Fix the problem that has appeared with the buttons that have no style associated.
Reverting the button.Button last change of using @JvmOverloads as that clearly breaks it.
Before:
After:
> ANDROID-13681 Revert using JvmOverloads in Button

- library/src/main/java/com/telefonica/mistica/compose/popover/PopOver.kt
Ticket: https://jira.tid.es/browse/ANDROID-13761
Popovers in compose are made with a custom library called balloon. It renders a composeView inside some view hierarchy.
So it is needed to set the semantics at this point.
> ANDROID-13761 Adding semantics to the popover

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/CalloutsCatalogFragment.kt
- library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
- library/src/main/java/com/telefonica/mistica/compose/button/ButtonSizes.kt
- library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
- library/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
Improve Callout buttons margin. Check 'How can I test this?' section to see the main differences.
* Improve Margins definition for Callout compose Component
* Remove link buttons horizontal margin
|  Before   | After   | Touch target size | 
| ------------- |-------------|-------------|
|  <img width="346" alt="actual_bad" src="https://github.com/Telefonica/mistica-android/assets/51969539/eaf3954f-dbd3-4c40-826d-009f681eb579">  | <img width="345" alt="after_good" src="https://github.com/Telefonica/mistica-android/assets/51969539/f2ce4146-2dc8-40a0-a57e-c0113afa9a57"> | <img width="341" alt="after_touch_area" src="https://github.com/Telefonica/mistica-android/assets/51969539/b794c9f7-a09a-4df8-a82b-63f727d214a5"> |
> Android-13783 Improve Callout buttons margin

- library/src/main/java/com/telefonica/mistica/button2/Button.kt
- library/src/main/res/layout/sheet_bottom_actions.xml
Make button2.button text xml attribute optional
* Check if returned value from typedArray is null
* Set empty in this case
> Make text button optional fix #ANDROID-13854

- library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
There is a UI glitch when a button2 with "link" style and chevron is rendered because of how chevron height is calculated. See the following video:
https://github.com/Telefonica/mistica-android/assets/47142570/e02ac130-279c-4296-b6ae-a7a0e9a35ad6
Use built in `IntrinsicSize.Min` as the chevron height instead of listening to the height of the text which makes the chevron to switch from big to small very quickly.
https://github.com/Telefonica/mistica-android/assets/47142570/7236b0bb-55f9-4c01-abf9-209738f50081
> ANDROID-14001 Fix chevron glitch on button link

- .lycheeignore
Ignore appcenter link in link checker as it's failing because the user-agent of the request is not a browser.
> ANDROID-13896 Ignore appcenter link in link checker

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/ListsCatalogFragment.kt
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Lists.kt
- catalog/src/main/res/layout/screen_fragment_lists_catalog.xml
- library/src/main/java/com/telefonica/mistica/compose/list/ListRowIcon.kt
- library/src/main/java/com/telefonica/mistica/compose/shape/Circle.kt
- library/src/main/java/com/telefonica/mistica/list/ListRowView.kt
- library/src/test/java/com/telefonica/mistica/compose/list/ListRowItemKtTest.kt
- library/src/test/java/com/telefonica/mistica/list/ListRowViewTest.kt
- library/src/test/res/layout/test_list_row_view.xml
Until now the assets in ListRow didn't have a possible interaction different from the rest of the row but this should be allowed as it has been defined in the specs: https://www.figma.com/file/Be8QB9onmHunKCCAkIBAVr/%F0%9F%94%B8-Lists-Specs?type=design&node-id=0%3A608&mode=design&t=lG2wUE8oNXAI5z4d-1
- Added setAssetOnClickListener for traditional views.
- Made the modifier accessible for the different ListRowIcon so they can be made clickable.
- Added tests for the traditional views and compose elements.
- Added a row example in the catalog at the end.
- Also added some section titles in the compose catalog as the traditional views already had.
In the catalog.
Classic views:
Compose:
> ANDROID-14134 Set assets clickable

- .github/actions/generate-html-report/scripts/generate-html-report.sh
- build.gradle
- library/build.gradle
Update roborazzi from 1.4.0 to the latest stable version 1.7.0
- Update the lib.
- Update the location where the compare images are created.
- Also updated roboelectric and ui-test-manifest
https://github.com/Telefonica/mistica-android/actions/runs/7298913782
https://github.com/Telefonica/mistica-android/actions/runs/7298905162
> ANDROID-14133 Update roborazzi to 1.7.0

- library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
Fix BottomSheet actions fonts error.
* Using containers context. Same context as other views.
Before: https://github.com/Telefonica/mistica-android/assets/8106237/dd95ad13-4cb2-4c32-a124-5a6c746a5796
After: https://github.com/Telefonica/mistica-android/assets/8106237/e9905095-c07e-4951-bf26-4a3268d8fe96
> ANDROID-14117 Using containers context as others methods

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Texts.kt
- catalog/src/main/res/layout/text_presets_fragment_catalog.xml
- library/src/main/java/com/telefonica/mistica/compose/theme/MisticaTheme.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/BlauBrand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/Brand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/MovistarBrand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/O2Brand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/TelefonicaBrand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/VivoBrand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/VivoNewBrand.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/text/MisticaTypography.kt
- library/src/main/res/values/styles_fonts.xml
Add preset-9 and preset-10 to Mistica app. These new presets have just been defined on figma, but not implemented.
_Provide a description of the implementation. A list of steps would be ideal._
* _Add them to compose: create new properties for Brand and set inside brands_
* _Add to xml_
* _Add new Texts for the app both compose and xml tabs_
> ADD - new presets #ANDROID-14321

- library/src/main/java/com/telefonica/mistica/compose/list/ListRowIcon.kt
- library/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
Currently the ListRowItem component in Mistica only admits a "ListRowIcon" param where we can only define a painterResource. This limitation causes that Icon types are tinted with default color (Black) instead of its original color.
We need to add a new optional param to allow original tint (tint= Color.Unspecified) or a custom tint color.
* Create new optional parameter "tint: Color? = null" for Icon builders data classes.
* Use this value when composing the Icon.
* If it's not provided (null) use the default color keeping the same behavior as before.
> ANDROID-14416 Allow tint for RowItem icons

- build.gradle
Update roborazzi in mística to have the latest updates and fixes of the lib and to then check its accessibility debug info in training sessions.
- Updating roborazzi version to 1.10.1
- Force error in screenshots on another branch and checking that the report is ok.
This branch:
Forced errors:
And the report:
> ANDROID-14406 update roborazzi to 1.10.1

- library/src/main/java/com/telefonica/mistica/sheet/SheetModel.kt
- library/src/main/java/com/telefonica/mistica/sheet/children/list/ListElementViewData.kt
- library/src/main/java/com/telefonica/mistica/sheet/children/list/adapter/ActionsListAdapter.kt
- library/src/main/java/com/telefonica/mistica/sheet/viewDataModelMappers.kt
- library/src/main/java/com/telefonica/mistica/util/AccesibilityElementType.kt
Expose the bottom sheet actions content description so that any app can pass a content description for that elements.
Also add AccesibilityElementType in there as an enum for links and buttons.
- Expose contentDescription in Sheet component by adding it to RowAction and the mapper and adapter of it.
- Added AccessibilityElementType as this is going to be used in android and iOS for accessibility strings.
I've created a version in maven local and then used it in novum adding " link" to the content description of these actions and checked with talkback (enable audio):
https://github.com/Telefonica/mistica-android/assets/13270085/ef9ea1f7-b569-4727-a7ab-e1db1f85876a
> ANDROID-14490 expose content description in sheet actions

- library/src/main/res/values-de/strings_content_descriptions.xml
- library/src/main/res/values-en/strings_content_descriptions.xml
- library/src/main/res/values-es/strings_content_descriptions.xml
- library/src/main/res/values-pt/strings_content_descriptions.xml
- library/src/main/res/values/strings_content_descriptions.xml
Update string used for closing the bottom sheet as content description.
- Asking for the translation and updating it.
The translations:
es_es: Cerrar ventana
de_de: Fenster schließen
en_us: Close window
pt_br: Fechar janela
(turn the volume ON)
https://github.com/Telefonica/mistica-android/assets/13270085/6adbb667-10e5-4f6f-9264-5e888b3659d4
> ANDROID-14548 update close translation

- library/src/main/java/com/telefonica/mistica/emptystate/screen/EmptyStateScreenView.kt
We need to show the fullWidth mode image to fit entire screen
* Add else condition to set CenterCrop in full_width mode
BEFORE
AFTER
> Update full width scaleType to center crop

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Titles.kt
- catalog/src/main/res/layout/title_catalog.xml
- library/src/main/java/com/telefonica/mistica/compose/title/Title.kt
- library/src/main/java/com/telefonica/mistica/list/ListRowView.kt
- library/src/main/java/com/telefonica/mistica/title/TitleView.kt
- library/src/main/res/values/attrs_components.xml
- library/src/test/java/com/telefonica/mistica/compose/title/TitleKtTest.kt
- library/src/test/java/com/telefonica/mistica/title/TitleViewTest.kt
The title of TitleView component should be able to be set with accessibility heading.
- Add isTitleHeading to TitleView
- Add isTitleHeading parameter to Title composable
- Add few samples in the catalog.
https://github.com/Telefonica/mistica-android/assets/13270085/0cc6d8c6-9fb9-4e40-8e37-0e4bf754678a
> ANDROID-14597 title view heading

- library/src/main/java/com/telefonica/mistica/list/ListRowView.kt
Cache backgroundType for reset row texts if needed during an android recycling loop.
* Exposing three new methods to reset that labels.
* Also instead another three methods to change its color.
_This does not show a change in the behavior of the row. It has only been modified for testing purposes._
[Screen_recording_20240508_104508.webm](https://github.com/Telefonica/mistica-android/assets/8106237/d7e2f2c2-16a3-4a25-9fa0-106344d78425)
> ANDROID-14620 Reset text color labels 

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Buttons.kt
- catalog/src/main/res/layout/screen_buttons_catalog.xml
- library/src/main/java/com/telefonica/mistica/button/ProgressButton.kt
- library/src/main/java/com/telefonica/mistica/button2/Button.kt
- library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
Improve button component accessibility. 
By default, the content description of a button is the text, but we need to give support to add a custom one in our custom implementations.
* Progress button (XML):
* It's a custom view with several buttons and views internally, we have to configure which is the important button for accessibility and ignore the others.
* Button2 (XML using compose internally):
* We have to ignore the custom view and pass the content description to the compose component that we use internally.
* Button (compose):
* Add a new parameter to customize the content description.
* Use this custom content description in the internal Text.
- You can review the result in this video (audio on):
https://github.com/Telefonica/mistica-android/assets/2582348/00f79bdf-92a8-4e3f-b8e7 …
> ANDROID-13801 Improve buttons accessibility

- .github/PULL_REQUEST_TEMPLATE.md
- library/src/main/java/com/telefonica/mistica/compose/theme/brushes/MisticaBrushesAutogenerated.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/color/MisticaColorsAutogenerated.kt
- tokens/src/main/java/com/telefonica/mistica/tokens/compose/GenerateMisticaBrushes.kt
- tokens/src/main/java/com/telefonica/mistica/tokens/compose/GenerateMisticaColors.kt
[ANDROID-14711](https://jira.tid.es/browse/ANDROID-14711)
With Mistica 12.0.0 copy method was removed, which was used by Latch to override some colors for MisticaColors. With these setters being internal, these cannot be modified from outside mistica.
Just remove internal setter limitation.
* Adapt scripts to not generate "internal set" modifier for MisticaColors and MisticaBrushes
* Run script to update classes
> ANDROID-14711 Allow setting colors from outside now that copy method has been deleted from MisticaColors and MisticaBrushes

- library/src/main/java/com/telefonica/mistica/emptystate/screen/EmptyStateScreenView.kt
- library/src/main/res/layout/empty_state_screen_view.xml
In EmptyStateScreenView when the image type is IMAGE_SIZE_FULL_WIDTH it loads the image in full width but it doesn't use the ratio of 16:9 to assign the height. As it's also using ScaleType.CENTER_CROP as scale type it results in the image being cropped.
- In order to not having to add a GlobalLayoutListener in order to calculate the height async that would result in the image blinking the simplest way is to update the layout so that the image is inside a ConstraintLayout instead of a LinearLayout and that way the aspect ratio can be used to get the height.
before:
after:
And when applied to vivo:
| Before        | After           |
| ![update_screen_before](https://github.com/Telefonica/mistica-android/assets/13270085/ce37d927-8db2-4dcc-ad17-fd5ed3f61ef1) …
> ANDROID-14761 Fix Image size of EmptyStateScreenView when it's IMAGE_SIZE_FULL_WIDTH

- .github/workflows/release.yml
Not include release notes in the release notification. Just include the link to the release to avoid errors when it contains markdown.
I've checked with the GitHub API that `html_url` is the right field:
> ANDROID-14628 Not include release notes in the release notification

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/BadgesCatalogFragment.kt
- catalog/src/main/res/layout/screen_badges_catalog.xml
- library/src/main/java/com/telefonica/mistica/badge/Badge.kt
Fix a bug when a Badge with lower width is set after a higher width badge.
* Just adapt catalog code to be able to reproduce the bug
* Clear the old badge before set a new one.
> ANDROID-14752 Fix Badge

- library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
Set BottomSheet title as Heading for accessibility.
- Set the bottom sheet title as heading.
Before: (video with audio)
https://github.com/Telefonica/mistica-android/assets/13270085/4412f321-7a6f-4df2-84a8-78bc66425e23
After: (video with audio)
https://github.com/Telefonica/mistica-android/assets/13270085/6b112904-5323-4b57-bfa5-0ad78735ae80
> ANDROID-14887 update set BottomSheet title as Heading for a11y

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Titles.kt
- catalog/src/main/res/layout/title_catalog.xml
- library/src/main/java/com/telefonica/mistica/compose/title/README.md
- library/src/main/java/com/telefonica/mistica/compose/title/Title.kt
- library/src/main/java/com/telefonica/mistica/title/README.md
- library/src/main/java/com/telefonica/mistica/title/TitleView.kt
- library/src/main/res/layout/title.xml
- library/src/main/res/values/attrs_components.xml
As figma definition title link could have chevron. 
* Add chevron option to compose and xml title element
> Add chevron option to title link

- library/src/main/res/layout/empty_state_screen_view.xml
- library/src/main/res/layout/highlighted_card_view.xml
- library/src/main/res/values/dimens_buttons.xml
Check that all sides margins of Mistica elements are 16dp (and not 24dp)
-Checked Mistica catalog using layout inspector to check sides margins
-Replaced 24dp with 16dp
Only found empty state xml implementation which used 24dp of side margins
I also found that link button of card_actions_view uses a negative margin. I think this should be reviewed in another task
Before
After
> ANDROID-14803 Update all the 24dp lateral margins to 16dp

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Inputs.kt
- catalog/src/main/res/layout/screen_inputs_catalog.xml
- library/src/main/java/com/telefonica/mistica/compose/input/NumberInput.kt
- library/src/main/java/com/telefonica/mistica/input/TextInput.kt
- library/src/main/res/layout/input_text_number.xml
- library/src/main/res/values/attrs_components.xml
- library/src/main/res/values/styles_forms.xml
Add number input to xml and compose views
* Add Number input composable with decimal check (avoiding add symbols or characters)
* Add Number input attr to xml view with numberDecimal input type
> ANDROID-15025 add number input

- library/src/main/java/com/telefonica/mistica/compose/theme/brand/BlauBrandFontSizesAutogenerated.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/MovistarBrandFontSizesAutogenerated.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/O2BrandFontSizesAutogenerated.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/O2NewBrandColorsAutogenerated.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/O2NewBrandFontSizesAutogenerated.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/TelefonicaBrandFontSizesAutogenerated.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/TuBrandFontSizesAutogenerated.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/VivoBrandFontSizesAutogenerated.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/VivoNewBrandColorsAutogenerated.kt
- library/src/main/java/com/telefonica/mistica/compose/theme/brand/VivoNewBrandFontSizesAutogenerated.kt
- library/src/main/res/values/attrs_autogenerated.xml
- library/src/main/res/values/themes_blau_autogenerated.xml
- library/src/main/res/values/themes_movistar_autogenerated.xml
- library/src/main/res/values/themes_o2New_autogenerated.xml
- library/src/main/res/values/themes_o2_autogenerated.xml
- library/src/main/res/values/themes_telefonica_autogenerated.xml
- library/src/main/res/values/themes_tu_autogenerated.xml
- library/src/main/res/values/themes_vivoNew_autogenerated.xml
- library/src/main/res/values/themes_vivo_autogenerated.xml
Update tokens to fix color contrast in bottom nav bar texts
> ANDROID-15030- Fix contrast in AppBar label

- library/build.gradle
_We need to fix compose Lottie animations._
_Update the library's version to 6.5.0._
_Projects such as Latch, Wallet and Smart Wifi had to update its Lottie version to that one in order to make its animations work._
- _Navigate to Feedbacks, configure one with an animation and show a classic and compose Feedback component. See that it is displayed as expected._
- _After that, we should generate a version and check that client projects need not to update its Lottie version in order to fix the reported issue._
https://github.com/user-attachments/assets/1f3ce9ee-d01e-420b-ada5-4d71b58ce54e
https://github.com/user-attachments/assets/50ee0f69-02f2-4265-bd79-4af30184ae37
> ANDROID-14756 fix lottie animations

- .github/workflows/release.yml
Use specific version when notifying Teams to avoid unexpected changes.
> Use specific version when notifying Teams

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Badges.kt
- library/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
- library/src/main/java/com/telefonica/mistica/compose/list/README.md
Clean unneded ExperimentalMaterialApi annotations.
Removing unneded annotations
No changes in code or screens, just removed annotations.
> ANDROID-15211 Remove unneded ExperimentalMaterialApi annotations

- library/src/main/java/com/telefonica/mistica/compose/list/ListRowItem.kt
Set icon as null when there is no icon. Due to this, the left padding was wrong in the compose list row item because we were adding an extra space because the icon was not null.
| Before        | After           |
| <img src="https://github.com/user-attachments/assets/2698067f-5d9e-4a86-93df-52516b683324" alt="drawing" width="200"/>      | <img src="https://github.com/user-attachments/assets/a9c5e319-fb8a-4eec-b632-8307a10e9166" alt="drawing" width="200"/> |
> ANDROID-15206 Set icon as null when there is no icon

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/ListsCatalogFragment.kt
- library/src/main/java/com/telefonica/mistica/button/ProgressButton.kt
- library/src/main/java/com/telefonica/mistica/compose/carousel/CarouselPagerIndicator.kt
- library/src/test/java/com/telefonica/mistica/compose/carousel/CalculateItemsTest.kt
- library/src/test/java/com/telefonica/mistica/compose/carousel/CalculateWindowPositionTest.kt
Fix suppress LongMethod
- Remove the suppressions of LongMethod.
- Added some private methods to make the previous long methods smaller.
- Scoutting: Removing the annotation ExperimentalPagerApi which was then suppressed in the same file with the OptIn.
https://github.com/user-attachments/assets/9db92577-046d-4e3a-b09e-32fc22517535
> ANDROID-15230 Fix suppressed long method

- library/src/main/java/com/telefonica/mistica/button/ProgressButton.kt
Fix acceptance errors of v15.0.1. PerformClick call was causing double calls to progressButton. Also if you scroll starting from the button, lifting your finger activates the button.
Deleted performClick call and added SuppressLint annotation
Tested [in this PR](https://github.com/Telefonica/android-messenger/actions/runs/11703406958/job/32593677318?pr=2452) with this [snapshot (15.0.1.2-SNAPSHOT)](https://github.com/Telefonica/mistica-android/actions/runs/11702882702/job/32592000326)
> Fix acceptance errors of v15.0.1

- library/src/main/java/com/telefonica/mistica/compose/input/CharsCounter.kt
- library/src/main/java/com/telefonica/mistica/compose/input/EmailInput.kt
- library/src/main/java/com/telefonica/mistica/compose/input/NumberInput.kt
- library/src/main/java/com/telefonica/mistica/compose/input/PasswordInput.kt
- library/src/main/java/com/telefonica/mistica/compose/input/PhoneInput.kt
- library/src/main/java/com/telefonica/mistica/compose/input/SearchInput.kt
- library/src/main/java/com/telefonica/mistica/compose/input/TextAreaInput.kt
- library/src/main/java/com/telefonica/mistica/compose/input/TextInput.kt
- library/src/main/java/com/telefonica/mistica/compose/input/TextInputImpl.kt
- library/src/main/java/com/telefonica/mistica/compose/input/TextInputTestTags.kt
- library/src/main/java/com/telefonica/mistica/compose/input/Underline.kt
Test IDs for input component (only compose by now)
I added the following IDs:
- TextField
- PasswordField
- SearchField
- PhoneNumberField
- EmailField
- DecimalField
- label
- helperText
- endHelperText
- errorText
- startIcon
- endIcon
Following IDs weren't added because associated input fields or features are not implemented yet:
- CreditCardexpirationField
- CreditCardNumberField
- CvvField
- DateField
- DateTimeField
- IbanField
- IntegerField
- MonthField
- PinField
- placeholder
> ANDROID-15325 Compose Input test ids

- library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
- library/src/main/java/com/telefonica/mistica/sheet/children/list/adapter/InformativeListAdapter.kt
- library/src/main/res/layout/sheet_list_row_informative.xml
_We need a divider in the informative sheet recycler view to match [design's specification](https://www.figma.com/design/nxToAYk7FGC86TS0mY61TU/%F0%9F%94%B8-Sheet-Specs?node-id=1960-11572&node-type=frame&t=GY2xRf2pOjf1qSDX-0)._
- Use our existing custom recycler view extension **configureWithFullWidthLayout** when we are configuring the informative sheet recycler.
- Do some modifications within InformativeListAdapter and sheet_list_row_informative.xml to have item spacing exactly as shown in the spec.
Right after invoking **configureWithFullWidthLayout** the UI was like this.
After modifying InformativeListAdapter to have below space in all cases, the UI was like this because this below space was 8dp (whereas figma's space is 16dp).
This is the final result.
| Before        | After …
> ANDROID-15374 divider implemented in informative sheet

- build.gradle
- catalog/build.gradle
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Tags.kt
- library-test-utils/build.gradle
- library/build.gradle
Related to https://jira.tid.es/browse/ANDROID-15454. Upgrade material lib in mistica, which is used by android-messenger.
Tagged as breaking change because it does not exposes anymore the internal libraries as api, so apps may need to declare their dependencies explicitly.
* Just raise version & review catalog components are working correctly with new material version.
> ANDROID-15581 Upgrade material lib & do not expose internal dependencies as api

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/DataCardFragment.kt
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/ListsCatalogFragment.kt
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/TagsCatalogFragment.kt
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/DataCards.kt
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/PosterCards.kt
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Tags.kt
- catalog/src/main/res/layout/screen_tags_catalog.xml
- library/src/main/java/com/telefonica/mistica/compose/tag/Tag.kt
- library/src/main/java/com/telefonica/mistica/tag/TagView.kt
- library/src/main/res/values/attrs_components.xml
Update tag color tokens and remove inverse.
Discussion about the colors and the inverse removal:
https://teams.microsoft.com/l/message/19:9d2d0d5e2fb6472bb80f534bd702cf20@thread.tacv2/1736771738837?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=e265fe99-929f-45d1-8154-699649674a40&parentMessageId=1736771738837&teamName=M%C3%ADstica&channelName=design-appscore&createdTime=1736771738837&ngc=true
- Updated tag tokens following the figma design.
- Removed inverse type (breaking change, Active should be used instead)
| Before        | After           |
| <image src="https://github.com/user-attachments/assets/5f2ddd3e-8a36-4a4b-a1b5-840bc945b588" alt="classic views before" width="200" />      | <image …
> SMARTWIFI-10829 tags update

- library/src/main/java/com/telefonica/mistica/compose/input/CheckBoxInput.kt
`CheckBoxInput` implementation was changed here https://github.com/Telefonica/mistica-android/pull/400 and now the whole `Row` that wraps the `Checkbox` and `TextWithLinks` composables is toggable.
That is more correct in terms of a11y but unexpectedly it has broken some tests in client apps when trying to click on a checkbox with links. The reason is because trying to do some click on a `CheckBoxInput` with a given `testTag` it ends up in a click on the middle of the wrapping `Row` previously mentioned and it may open any link if present.
To prevent that we propose to add some inner testTag to the single Checkbox.
Adding some test tag to the `Checkbox` composable from material user under the hood by `CheckBoxInput`
> ANDROID-15643 Add test tag to Checkbox

- CONTRIBUTING.md
_Updating CONTRIBUTING.md's Pull Requests section._
_Replace_
```
We would love to accept your Pull Requests but please, before starting your development,
[create an issue](https://github.com/Telefonica/mistica-android/issues/new/choose).
Include someone from **Telefonica/mistica-design** team as reviewer.
```
_with_
```
We would love to accept your Pull Requests but please
- Before starting your development, [create an issue](https://github.com/Telefonica/mistica-android/issues/new/choose).
- Once the pull request is created, make sure that you add someone from **Telefonica/mistica-design** team as reviewer to it.
```
_Open [CONTRIBUTING.md](https://github.com/Telefonica/mistica-android/blob/jmanriquehiberus-patch-1/CONTRIBUTING.md) and make sure the text is correct._
> Adding verbosity to the Pull Requests section

- library/src/main/java/com/telefonica/mistica/button/ProgressButton.kt
- _Prior to these changes, there were two focus points in the ProgressButton when we used a wireless keyboard or had talkback activated._
- _We need to have one single focus point in the progress button, as done with all other buttons._
_As you can see [here](https://developer.android.com/reference/android/view/ViewGroup#attr_android:descendantFocusability), the descendantFocusability attribute value, afterDescendants, forces the element to gain focus only once._
_Modifying the frame layout attribute to afterDescendants fixes the issue._
- Connect a wireless keyboard.
- Navigate to the buttons list.
- Press tab to move the focus among elements.
- See that the "Primary progress" button is only focused once.
https://github.com/user-attachments/assets/9b37b104-442c-41a9-9432-20140d412337 …
> ANDROID-15625 fix two focus points in progress button

- .github/workflows/catalog.yml
- .github/workflows/debug_catalog.yml
- .github/workflows/snapshot.yml
Add firebase distributions for mistica, without removing appcenter publications. As commented, it's not possible to use private shared workflows from public repositories.
* Just add required steps for existing publications
> ANDROID-15834 Firebase distributions for Mistica

- library/src/main/java/com/telefonica/mistica/feedback/screen/view/FeedbackScreenView.kt
- library/src/main/res/layout/screen_feedback.xml
In the feedback component in mística the image, title, subtitle are read grouped by talkback.
Also the title should be set as a heading.
This PR is in order to fix that.
- Removed focusable on the LinearLayout that made the elements be grouped.
- Set the title as heading.
**_Turn up the volume on the videos_**
| Before        | After           |
| <video src="https://github.com/user-attachments/assets/eb9127f0-94c8-412f-a117-74d69252566c" alt="Before" width="200"/>      | <video src="https://github.com/user-attachments/assets/4ae8c36a-aadc-43f2-823a-5bbbab50e148" alt="After" width="200"/> |
> ANDROID-15982 Fix feedback Accessibility

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/CalloutsCatalogFragment.kt
- catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Callouts.kt
- library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
- library/src/main/java/com/telefonica/mistica/callout/README.md
- library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
- library/src/main/res/layout/callout_view.xml
- library/src/main/res/values/attrs_components.xml
- Make the title view configurable so that talkback treats it as a header or not. By default, **it will always** be a header.
- Make the close/dismiss button the last node in the accessibility hierarchy.
* Expose a method to configure "heading"
* Set close/dismiss button to be the last in the hierarchy
* Fixed XML view close/dismiss button touch zone.
| Focus Before        | Focus After           |
| <img src="https://github.com/user-attachments/assets/9029ac74-5757-4cb5-b13e-02da9ff58b01" alt="drawing" width="200"/> | <img src="https://github.com/user-attachments/assets/07b3be78-a84e-4255-b119-a12426fd0312" alt="drawing" width="200"/>      |
| A11y XML        | A11y Compose           |
| <video …
> ANDROID-15018 Callout a11y

- library/src/main/res/layout/callout_view.xml
We came from: https://github.com/Telefonica/mistica-android/pull/413
Making XML close button accesible, making it bigger, espresso found a problem due close button container has a padding to  apply a visual margin its children.
The main point is the transalation property with negative value. Visually the button is displayed perfectly, but, espresso have a problem with that, due it thinks that the button is "partly hidden".
* Redistribute margins
| Before        |  After           |
| <img src="https://github.com/user-attachments/assets/33a9e201-88ca-4dee-9fb0-e5238341913e" alt="drawing" width="200"/> | <img src="https://github.com/user-attachments/assets/a23828b2-cd39-42b0-bc7a-61f501fd6695" alt="drawing" width="200"/>      |
> ANDROID-16024 Let component set its margin

- .github/workflows/release.yml
Fix new release notification, instead of using `skitionek/notify-microsoft-teams` GA, I'm making a POST request directly with the adaptive card that we want to show.
- I've tested with a manual workflow and the message appears ok in Teams
> ANDROID-16028 Fix new release notification

- .github/workflows/link_checker.yml
Issue comes from the action to check links. This issue has been reported by more users -> https://github.com/lycheeverse/lychee-action/issues/289
Ticket to update action version when solved -> https://jira.tid.es/browse/ANDROID-16194
* Disable execution on pull requests
* Add worflow_dispatch event to allow launching it manually to test it properly when this issue is fixed.
> ANDROID-16195 Disable Links checker as it is failing due github rate limit issues

- .github/workflows/import-design-tokens.yml
[ANDROID-16193](https://jira.tid.es/browse/ANDROID-16193)
Update description for design tokens update PRs that are automatically created so additional context is provided.
The expectation is that whether design token PRs are manually generated from this repo or from mistica-design, they should always have context in the description about the changes requested so reviewers are informed.
Just update the PR body
> Explicitly ask for additional context in design token update PRs

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
Sometimes CentralPortal publication went wrong
* Use `closeAndReleaseStagingRepositories`
* Using `closeAndReleaseStagingRepository` probably was using `closeAndReleaseOtherNexusStagingRepository` or `closeAndReleaseSonatypeStagingRepository `
* https://github.com/gradle-nexus/publish-plugin?tab=readme-ov-file#summary-tasks
> ANDROID-16222 Minor fix on CentralPortal publication

- catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/ListsCatalogFragment.kt
- library/src/main/java/com/telefonica/mistica/list/ListRowView.kt
- library/src/main/java/com/telefonica/mistica/list/README.md
- library/src/main/res/values/attrs_components.xml
- library/src/test/java/com/telefonica/mistica/list/ListRowViewTest.kt
[ANDROID-15258](https://jira.tid.es/browse/ANDROID-15258)
ℹ️ **Only for XML implementation**. The Compose implementation will be added in this other task: https://jira.tid.es/browse/ANDROID-15075
- Allow to provide a custom label in informative rows to be read by screen readers in a single focus, instead reading all elements one by one.
- Hide always badges to Screen readers no matter if the list is informative or interactive
For more info, check out this Figma documentation: https://www.figma.com/design/Be8QB9onmHunKCCAkIBAVr/%F0%9F%94%B8-Lists-Specs?node-id=4615-10678&t=eRMRYwPaobn7VxjU-4
* Remove badgeDescription implementation.
* Managing the coexistence both contentDescription:
* Default: handled by the component itself
* Custom: managed by the implementation
* Create unitTests for …
> ANDROID-15258 List accessibility update for XML implementation
